name: HexacoreCliente
options:
  bundleIdPrefix: com.hexacore
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  HexacoreCliente:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: HexacoreCliente
    info:
      path: HexacoreCliente/Resources/Info.plist
      properties:
        CFBundleDisplayName: HEXACORE Cliente
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSPhotoLibraryUsageDescription: HEXACORE usa tu galería para elegir la foto de tu perfil.
        UIUserInterfaceStyle: Automatic
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hexacore.cliente
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: NO
